### ISSUE TITLE
Help on training new vocals

### ISSUE THREAD

**Issue by haru0l** [SJTMusicTeam/Muskits#11]
Hi, I'm looking to train some new vocals on here. I'm used to training NNSVS, but is there a guide for training here? Thanks.

**Comment by ftshijt** [comment]
Hi, thanks for your interest in our project. We are still working on the first release. The time is expected in early October.

**Comment by dtx525942103** [comment]
wait for a guide for training, too. this project is very attractive!

**Comment by Nan-Huo** [comment]
> wait for a guide for training, too. this project is very attractive!

We will update the guide in a week. Thank you for your interest!

**Comment by ftshijt** [comment]
Hi, we have updated the tutorial at https://github.com/SJTMusicTeam/Muskits/blob/main/doc/tutorial.md 

Noted that we are still refining the codebase with more features and functionalities. so there might be some issues in the codebase now. We expect to make it robust and stable in late March. Feel free to give your suggestions and comments on our project. 

Many thanks!
