### ISSUE TITLE
Demo samples for Japanese

### ISSUE THREAD

**Issue by r9y9** [SJTMusicTeam/Muskits#113]
This is not a bug report but more like a question. I am reading Muskits's paper https://arxiv.org/abs/2205.04029 and am curious to listen to samples used in the single-speaker and multi-speaker experiments. Are the JP samples available? Also, do you have plans to add real-time demos for Japanese? Thanks!

**Comment by ftshijt** [comment]
We did not put it on the open domain yet, but definitely will update the demo with as many recipes are trained in JP :-)
