### ISSUE TITLE
How shall I write the text transcription to adapt my own data

### ISSUE THREAD

**Issue by funkgeek** [SJTMusicTeam/Muskits#116]
Hi. This is an amazing repo. I would like to use it, but with adaption on my own collected data. In the recipe it mentions the text is about transcription, and my two datasets will be Mandarin and English. For English data, shall I write the transcription in the phoneme level or utterance level? For Mandarin, shall I write Chinese character or pinyin, or annotating in phoneme level? Thank you

**Comment by ftshijt** [comment]
Thanks for your interest in our toolkits! We now do not support g2p (though you can find entries for those) yet. So we expect you have the transcription at the phoneme level. You can refer to other recipes for what the data would be like after preparation.

**Comment by ftshijt** [comment]
Note that our toolkit is merging to ESPnet, and we expect to take advantage of their g2p method during the merging. Please stay tuned

**Comment by ftshijt** [comment]
Similar to other non-autoregressive methods, our current implementation needs alignment (phoneme-audio). For TTS, that would be easier with autoregressive TTS or force aligner. But according to our experience, those methods are not robust for SVS with such limited data. So we now still need annotation for those.

Our team is recently studying for something more in the direction of alignment-free methods.
