### ISSUE TITLE
note dur and note pitch embedding is added with phone embedding or concat with embedding

### ISSUE THREAD

**Issue by 11721206** [SJTMusicTeam/Muskits#120]
Hello, I just want to know note dur and note pitch embedding is added with phone embedding or concat with embedding? my experiment show concat result is very bad when i change my note pitch. Thank You

**Comment by ftshijt** [comment]
Hi, Thanks for raising the question. Generally speaking, it depends on the models.

For Xiaoice, the embedding is added up as in https://github.com/SJTMusicTeam/Muskits/blob/3750a54f414761bb8bd72b1f0914b442d34cb176/muskit/svs/xiaoice/XiaoiceSing.py#L447
For transformer-based SVS, the embedding is either concat or added up as in https://github.com/SJTMusicTeam/Muskits/blob/3750a54f414761bb8bd72b1f0914b442d34cb176/muskit/svs/glu_transformer/glu_transformer.py#L758-L761 
For RNN-based model, the embedding is either concat or added up as in https://github.com/SJTMusicTeam/Muskits/blob/3750a54f414761bb8bd72b1f0914b442d34cb176/muskit/svs/naive_rnn/naive_rnn.py#L445-L450

**Comment by ftshijt** [comment]
Could you refer to which recipe you are working with so that we could check and even help you investigate the issues?

**Comment by ftshijt** [comment]
Since there is no response for a long time, I will close the issue
