### ISSUE TITLE
small question p2

### ISSUE THREAD

**Issue by dutchsing009** [SJTMusicTeam/Muskits#122]
Hey how are you !! i hope your team is doing okay too , I see some progress in the repo , and I just wanted to ask if there is an update to the release plans of the new singing papers , like vi-singer and hifisinger etc :) especially vi-singer as it is the best paper out of them

Feel free to close the issue after answering the question

**Comment by ftshijt** [comment]
Many thanks for your following of our toolkits. In short, yes, we have been working on new models. But the performances are not satisfactory for now. We would release all we have after the results sound good~ However, despite that part of development, we are mostly focusing on the migration to espnet and trying to make a more standardized data format for the music problems not limited to singing. 

Please stay in touch as we will continue updating the whole thing in the repo!
