### ISSUE TITLE
Opencpop stage 1 error

### ISSUE THREAD

**Issue by jerryuhoo** [SJTMusicTeam/Muskits#128]
https://github.com/SJTMusicTeam/Muskits/blob/8c692ffe668dec1c862ed7b35a03bc9f0c42c7b2/egs/opencpop/svs1/local/data.sh#L50
Should this be test instead of eval?
```shell
for src_data in train test; do 
```

**Comment by ftshijt** [comment]
Yeah, it is, we will change that. Thanks a lot for the fix.

**Comment by ftshijt** [comment]
Fixed~

**Comment by jerryuhoo** [comment]
Thanks!
