### ISSUE TITLE
support wenet's opencpop dataset?

### ISSUE THREAD

**Issue by dtx525942103** [SJTMusicTeam/Muskits#59]
https://wenet.org.cn/opencpop/ the first big chinese singing data

**Comment by ftshijt** [comment]
Many thanks for your interest. Yeah, we have noticed the corpus. We are actively prepared to add a recipe for that. Please stay tuned.

**Comment by ftshijt** [comment]
Hi, just for an update, we are now supporting opencpop in our toolkits (see https://github.com/SJTMusicTeam/Muskits/tree/main/egs/opencpop/svs1 ) Meanwhile, coming very recently, we are preparing for an open demonstration with our pre-trained models.

**Comment by dtx525942103** [comment]
waiting for you

**Comment by ftshijt** [comment]
Hi, thanks for your interest in our project. The demo is online now: https://colab.research.google.com/github/SJTMusicTeam/svs_demo/blob/master/muskit_svs_realtime.ipynb Please feel free to leave your comments and suggestions

**Comment by dtx525942103** [comment]
Thanks very much!
