### ISSUE TITLE
did here has any pre trainned model for directly download ?

### ISSUE THREAD

**Issue by imiskolee** [SJTMusicTeam/Muskits#66]
hi,all:

Did anyone success build a model for test?  can you share them?

**Comment by ftshijt** [comment]
Hi, thanks for your interest. As noted in readme, we are working on releasing a demonstration notebook for users to experience the real-time synthesis (with several of our pre-trained models). Given it's the Chinese new year this week, we probably will start to back on the week after next. Stay tuned!

**Comment by imiskolee** [comment]
> Hi, thanks for your interest. As noted in readme, we are working on releasing a demonstration notebook for users to experience the real-time synthesis (with several of our pre-trained models). Given it's the Chinese new year this week, we probably will start to back on the week after next. Stay tuned!

thanks! I already watch here.
