### ISSUE TITLE
which python version you use?

### ISSUE THREAD

**Issue by dtx525942103** [SJTMusicTeam/Muskits#82]

**Comment by Cardroid** [comment]
I succeeded in training the Kiritan recipe with Python version 3.8.10.

**Comment by ftshijt** [comment]
As far as we are concerned, versions from 3.7 to 3.9 should be working.

**Comment by dtx525942103** [comment]
my 3.6, so i think i need upgrade my python, thank you.

**Comment by ftshijt** [comment]
It might be OK, but we did not tested it on our side

**Comment by dtx525942103** [comment]
i upgrade python to 3.7, i success to generate wavs by your pretrained model. TKS
