### ISSUE TITLE
Will you consider implementing VISinger base on VITS?

### ISSUE THREAD

**Issue by dtx525942103** [SJTMusicTeam/Muskits#83]
VITS is the best TTS system, I think. So VISinger is attractive.
https://github.com/jaywalnut310/vits  is the path of VITS code.
https://zhangyongmao.github.io/VISinger/  is the demo of VISinger.

**Comment by ftshijt** [comment]
Many thanks for your suggestion! We are considering supporting GAN-based svs in our third iteration.

Here is a brief plan of the roadmap:
- By end of March, we want to refine the current codebase and support more recipes (as well as vocoders from https://github.com/kan-bayashi/ParallelWaveGAN)
- By end of May, we will start to merge the framework to ESPnet (you may find they are very similar) as a new sub-module ESPnet-Muskit
- By June, we expect to support GAN-based SVS and other frameworks including
    - https://www.arxiv-vanity.com/papers/1903.10729/
    - https://github.com/SoonbeomChoi/BEGANSing
    - VISinger
    - HifiSinger
    - DiffSinger

If you have more suggestions or comments, please feel free to request upon issues. Given requests, we may also change the priorities.

**Comment by dtx525942103** [comment]
good news
