### ISSUE TITLE
Can you recommend some study material of Singing voice synthesis  for beginners?

### ISSUE THREAD

**Issue by dtx525942103** [SJTMusicTeam/Muskits#84]

**Comment by ftshijt** [comment]
It's hard to say a general material for svs. My recommendation would be to start from existing reproducible codebases and their related papers (there are quite a few in recent years).

Also, here comes an ad, our team (Muskit) team is expecting more collaborators. At the same time over implementing many algorithms and features, we also care about educational perspective with new recipes and so on. If you are interested, please email ftshijt@gmail.com and we can have more discussion.
