### ISSUE TITLE
can not understand the label format

### ISSUE THREAD

**Issue by imiskolee** [SJTMusicTeam/Muskits#87]
hi,

where i can see the label format spec ?, can not understand what's AP SP

**Comment by ftshijt** [comment]
Hi, we are still working on releasing a tutorial on making recipes for new vocals. (We already have a running instructions for existing recipes, see README.md).

Currently, the label format is quite simple as 
<utt_id> <seg1_start> <seg1_end> <seg_label> <seg2_start> <seg2_end> <seg_label> etc.
We understand it would be problem for some applications and it is not easy to check, so we are also thinking about changing the format after we stabilize the other parts.


For AP, SP, I guess you are referring to world vocoder params (if not, please ignore). For that, please refer to the related repo https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoderfor more description

**Comment by dtx525942103** [comment]
SP & SPN offen appear in asr; SPN is spoken noise;
